# Generated by Django 2.2.17 on 2023-05-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0003_auto_20230326_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Логин', max_length=50)),
                ('password', models.CharField(help_text='Пароль', max_length=50)),
                ('name', models.CharField(help_text='Имя', max_length=50)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='posylka',
            options={'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Название города', max_length=50),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='cityArrival',
            field=models.ForeignKey(help_text='Город направления', on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='mo.City'),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='cityDestination',
            field=models.ForeignKey(help_text='Город отправления', on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='mo.City'),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена', max_digits=25),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='name',
            field=models.CharField(help_text='Название', max_length=50),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='pos_id',
            field=models.CharField(help_text='ID посылки', max_length=50),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='status',
            field=models.BooleanField(help_text='Статус посылки'),
        ),
        migrations.AlterField(
            model_name='posylka',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Вес', max_digits=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(help_text='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(help_text='Вопрос'),
        ),
    ]
