# Generated by Django 2.2.17 on 2023-05-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0004_auto_20230505_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.ForeignKey(help_text='Город', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='mo.City'),
        ),
    ]
