# Generated by Django 2.2.17 on 2023-05-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo', '0005_users_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='posylka',
            name='user',
            field=models.ForeignKey(help_text='Клиент', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='mo.Users'),
        ),
    ]
